# wrangler.toml - Configuration for your Cloudflare Worker

name = "jeremy-ai-proxy" # This should match the name you gave your Worker in Cloudflare UI
main = "worker/worker.js" # This points to the location of your Worker script
compatibility_date = "2025-07-16" # Use today's date or a recent one

# If you have any other build steps or settings, they would go here.
# For a simple JS worker, this is usually enough.
